version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    networks:
      - dove-lab-network
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: DOVE_LAB
      MYSQL_USER: dove_app
      MYSQL_PASSWORD: dove1234
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./scripts/init_data.sql:/docker-entrypoint-initdb.d/02_init_data.sql

  redis:
    image: redis:7-alpine
    container_name: dove-redis
    restart: always
    networks:
      - dove-lab-network
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:

networks:
  dove-lab-network:
