version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    networks:
      - dove-lab-network
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: DOVE_LAB
      MYSQL_USER: dove_app
      MYSQL_PASSWORD: dove1234
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./scripts/init_data.sql:/docker-entrypoint-initdb.d/02_init_data.sql
      - ./scripts/init_stock_data.sql:/docker-entrypoint-initdb.d/03_init_stock_data.sql
#      - ./scripts/init_indicator_data.sql:/docker-entrypoint-initdb.d/04_init_indicator_data.sql

volumes:
  mysql_data:

networks:
  dove-lab-network:
