rootProject.name = 'dove-lab'

include 'scheduler'
include 'api'
project(':scheduler').projectDir = file('application/scheduler')
project(':api').projectDir = file('application/api')

include 'krx'
include 'indicator'
include 'market'
include 'stock'
project(':krx').projectDir = file('infrastructure/krx')
project(':indicator').projectDir = file('domain/indicator')
project(':market').projectDir = file('domain/market')
project(':stock').projectDir = file('domain/stock')

include 'logging'
include 'jpa'
include 'api-quota'
include 'concurrent'
include 'datetime'
include 'job-status'
include 'workspace'
include 'screening'
project(':screening').projectDir = file('domain/screening')
project(':logging').projectDir = file('library/logging')
project(':jpa').projectDir = file('library/jpa')
project(':api-quota').projectDir = file('library/api-quota')
project(':concurrent').projectDir = file('library/concurrent')
project(':datetime').projectDir = file('library/datetime')
project(':job-status').projectDir = file('library/job-status')
project(':workspace').projectDir = file('library/workspace')


include 'user'
project(':user').projectDir = file('domain/user')

include 'auth'
project(':auth').projectDir = file('domain/auth')

include 'user-feature'
project(':user-feature').projectDir = file('domain/user-feature')

include 'investor-flow'
project(':investor-flow').projectDir = file('domain/investor-flow')

include 'system-event'
project(':system-event').projectDir = file('domain/system-event')

include 'kis'
project(':kis').projectDir = file('infrastructure/kis')

include 'stock-collection'
project(':stock-collection').projectDir = file('domain/stock-collection')

include 'model-serving'
project(':model-serving').projectDir = file('domain/model-serving')

include 'custom-metric'
project(':custom-metric').projectDir = file('domain/custom-metric')

include 'fundamental'
project(':fundamental').projectDir = file('domain/fundamental')

include 'dart'
project(':dart').projectDir = file('infrastructure/dart')
