INSERT INTO EXCHANGE_TRADING_DATE (EXCHANGE, TRADE_DATE, PRICES_SYNCED)
SELECT 'KRX', d.TRADE_DATE, 1
FROM (
    SELECT DISTINCT TRADE_DATE
    FROM STOCK_PRICE
    WHERE PRICE_TYPE = 0
      AND EXCHANGE IN (0, 1, 2)
) d
ON DUPLICATE KEY UPDATE PRICES_SYNCED = VALUES(PRICES_SYNCED);
