-- DOVE-LAB schema v2 (2026-05-30)

CREATE TABLE IF NOT EXISTS STOCK (
    TICKER              VARCHAR(20)  NOT NULL COMMENT '종목코드',
    ISIN                VARCHAR(12)           COMMENT 'ISIN',
    MARKET              VARCHAR(10)  NOT NULL COMMENT 'KOSPI/KOSDAQ/KONEX',
    LISTING_DATE        DATE,
    SECUGRP_NM          VARCHAR(40),
    KIND_STKCERT_TP_NM  VARCHAR(40),
    CREATED_AT          DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (TICKER),
    INDEX IDX_STOCK_ISIN (ISIN),
    INDEX IDX_STOCK_SECUGRP (SECUGRP_NM),
    INDEX IDX_STOCK_STKCERT (KIND_STKCERT_TP_NM),
    INDEX IDX_STOCK_MARKET (MARKET)
) COMMENT='종목 마스터';

CREATE TABLE IF NOT EXISTS STOCK_DETAIL (
    TICKER              VARCHAR(20)  NOT NULL,
    LISTED_SHARES       BIGINT,
    CAPITAL_AMOUNT      BIGINT,
    FACE_VALUE          BIGINT,
    STOCK_KIND_CD       VARCHAR(3),
    ETF_DVSN_CD         VARCHAR(2),
    REITS_KIND_CD       VARCHAR(1),
    KOSPI200_ITEM_YN    VARCHAR(1),
    IDX_BZTP_LCLS_CD    VARCHAR(3),
    IDX_BZTP_MCLS_CD    VARCHAR(3),
    IDX_BZTP_SCLS_CD    VARCHAR(3),
    IDX_BZTP_LCLS_NM    VARCHAR(60),
    IDX_BZTP_MCLS_NM    VARCHAR(60),
    IDX_BZTP_SCLS_NM    VARCHAR(60),
    STD_IDST_CLSF_CD    VARCHAR(6),
    STD_IDST_CLSF_NM    VARCHAR(130),
    FRNR_PSNL_LMT_RT    VARCHAR(24),
    TR_STOP_YN          VARCHAR(1),
    ADMN_ITEM_YN        VARCHAR(1),
    LSTG_ABOL_DT        VARCHAR(8),
    SCTS_MKET_LSTG_DT   VARCHAR(8),
    PRDT_NAME           VARCHAR(60),
    PRDT_ABRV_NAME      VARCHAR(60),
    PRDT_ENG_NAME       VARCHAR(60),
    SHTN_PDNO           VARCHAR(12),
    PRDT_RISK_GRAD_CD   VARCHAR(2),
    PRDT_CLSF_CD        VARCHAR(6),
    PRDT_CLSF_NM        VARCHAR(60),
    UPDATED_AT          DATETIME(6)  NOT NULL,
    PRIMARY KEY (TICKER),
    INDEX IDX_SD_PRDT_CLSF (PRDT_CLSF_CD),
    INDEX IDX_SD_BZTP_LCLS (IDX_BZTP_LCLS_NM),
    INDEX IDX_SD_BZTP_MCLS (IDX_BZTP_MCLS_NM),
    INDEX IDX_SD_BZTP_SCLS (IDX_BZTP_SCLS_NM),
    INDEX IDX_SD_STD_IDST (STD_IDST_CLSF_NM),
    INDEX IDX_SD_PRDT_CLSF_NM (PRDT_CLSF_NM)
) COMMENT='종목 상세';

CREATE TABLE IF NOT EXISTS STOCK_TAG_VALUE (
    ID          BIGINT       NOT NULL AUTO_INCREMENT,
    FIELD       VARCHAR(20)  NOT NULL COMMENT '분류 차원 (TagField 이름)',
    TAG_VALUE   VARCHAR(130) NOT NULL COMMENT 'KRX/KIS 분류 값 원문',
    LABEL       VARCHAR(130) NOT NULL COMMENT '화면 표시명 (기본=원문값)',
    CREATED_AT  DATETIME(6)  NOT NULL,
    UPDATED_AT  DATETIME(6)  NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_STV_FIELD_VALUE (FIELD, TAG_VALUE),
    INDEX IDX_STV_FIELD (FIELD)
) COMMENT='종목 분류 값 마스터 (수집 시 자동 등록, 표시명 편집)';

CREATE TABLE IF NOT EXISTS STOCK_EVENT (
    ID          BIGINT       NOT NULL AUTO_INCREMENT,
    TICKER      VARCHAR(20)  NOT NULL COMMENT '종목코드',
    EVENT_TYPE  VARCHAR(20)  NOT NULL COMMENT '이벤트 유형 (StockEventType)',
    EVENT_DATE  DATE         NOT NULL COMMENT '이벤트 기준일 (KSD record_date)',
    SUMMARY     VARCHAR(200) COMMENT '표시용 요약',
    DETAIL      TEXT         COMMENT 'KSD 원본 응답 JSON',
    SOURCE      VARCHAR(20)  COMMENT '수집 출처 (예: KIS_KSD)',
    CREATED_AT  DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID),
    UNIQUE KEY UK_SE_TICKER_TYPE_DATE (TICKER, EVENT_TYPE, EVENT_DATE),
    INDEX IDX_SE_TICKER_DATE (TICKER, EVENT_DATE),
    INDEX IDX_SE_EVENT_DATE (EVENT_DATE)
) COMMENT='종목 권리 이벤트 (배당·증자·감자·합병/분할·액면, KIS 예탁원정보)';

CREATE TABLE IF NOT EXISTS STOCK_PRICE (
    TICKER      VARCHAR(20)  NOT NULL,
    EXCHANGE    TINYINT      NOT NULL COMMENT '거래소 코드(KOSPI/KOSDAQ/KONEX/NXT/INTEGRATED)',
    PRICE_TYPE  TINYINT      NOT NULL COMMENT '가격유형 코드(RAW/ADJUSTED)',
    TRADE_DATE  DATE         NOT NULL,
    OPEN_PRICE  BIGINT,
    HIGH_PRICE  BIGINT,
    LOW_PRICE   BIGINT,
    CLOSE_PRICE BIGINT,
    VOLUME      BIGINT,
    TURNOVER    BIGINT,
    PRIMARY KEY (TICKER, EXCHANGE, PRICE_TYPE, TRADE_DATE),
    INDEX IDX_SP_TICKER_DATE (TICKER, TRADE_DATE),
    INDEX IDX_SP_EXCHANGE_DATE (EXCHANGE, TRADE_DATE)
) COMMENT='일별 주가';

CREATE TABLE IF NOT EXISTS STOCK_FEATURE_DAILY (
    TICKER            VARCHAR(20)  NOT NULL,
    EXCHANGE          TINYINT      NOT NULL COMMENT '거래소 코드',
    PRICE_TYPE        TINYINT      NOT NULL COMMENT '가격유형 코드',
    TRADE_DATE        DATE         NOT NULL,
    SEQ               INT          NOT NULL COMMENT '그룹 내 거래일 순번(전일·미래수익 비교용)',
    OPEN_PRICE        BIGINT,
    HIGH_PRICE        BIGINT,
    LOW_PRICE         BIGINT,
    CLOSE_PRICE       BIGINT,
    VOLUME            BIGINT,
    TURNOVER          BIGINT,
    SMA_5             FLOAT,
    SMA_10            FLOAT,
    SMA_20            FLOAT,
    SMA_50            FLOAT,
    SMA_60            FLOAT,
    SMA_120           FLOAT,
    SMA_200           FLOAT,
    EMA_5             FLOAT,
    EMA_10            FLOAT,
    EMA_20            FLOAT,
    EMA_60            FLOAT,
    EMA_120           FLOAT,
    EMA_200           FLOAT,
    RSI_9             FLOAT,
    RSI_14            FLOAT,
    RSI_21            FLOAT,
    MACD_LINE         FLOAT,
    MACD_SIGNAL       FLOAT,
    MACD_HISTOGRAM    FLOAT,
    STOCHASTIC_K_14_7 FLOAT,
    STOCHASTIC_D_14_7 FLOAT,
    ADX_14            FLOAT,
    PLUS_DI_14        FLOAT,
    MINUS_DI_14       FLOAT,
    VOLUME_RATIO_20   FLOAT,
    OBV               FLOAT,
    BB_UPPER_20       FLOAT,
    BB_MIDDLE_20      FLOAT,
    BB_LOWER_20       FLOAT,
    BB_PERCENT_B_20   FLOAT,
    BB_WIDTH_20       FLOAT,
    ATR               FLOAT,
    MFI               FLOAT,
    CCI               FLOAT,
    WILLIAMS_R        FLOAT,
    VOLATILITY_5D     FLOAT,
    VOLATILITY_20D    FLOAT,
    HIGH_20D_RATIO    FLOAT,
    HIGH_52W_RATIO    FLOAT,
    LOW_20D_RATIO     FLOAT,
    VOLUME_MA20_RATIO FLOAT,
    GAP_OPEN          FLOAT,
    RET_1D            FLOAT,
    RET_5D            FLOAT,
    RET_10D           FLOAT,
    BODY_RATIO        FLOAT,
    LOWER_WICK        FLOAT,
    IS_52W_HIGH       TINYINT,
    IS_52W_LOW        TINYINT,
    IS_20D_HIGH       TINYINT,
    IS_20D_LOW        TINYINT,
    CALCULATED_AT     DATETIME(6)  NOT NULL,
    PRIMARY KEY (TICKER, EXCHANGE, PRICE_TYPE, TRADE_DATE),
    INDEX IDX_SFD_EXCHANGE_DATE (EXCHANGE, PRICE_TYPE, TRADE_DATE),
    INDEX IDX_SFD_SEQ (TICKER, EXCHANGE, PRICE_TYPE, SEQ)
) COMMENT='종목·거래일별 지표(wide)' ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE IF NOT EXISTS INDICATOR_CURSOR (
    ID              BIGINT       NOT NULL AUTO_INCREMENT,
    TICKER          VARCHAR(20)  NOT NULL,
    EXCHANGE        TINYINT      NOT NULL COMMENT '거래소 코드',
    PRICE_TYPE      TINYINT      NOT NULL COMMENT '가격유형 코드',
    CURSOR_DATE     DATE         COMMENT 'NULL=1985-01-01부터',
    UPDATED_AT      DATETIME(6)  NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_IC (TICKER, EXCHANGE, PRICE_TYPE),
    INDEX IDX_IC_TICKER (TICKER)
) COMMENT='지표 계산 커서(그룹 단위)';

CREATE TABLE IF NOT EXISTS EXCHANGE_TRADING_DATE (
    EXCHANGE        VARCHAR(10)  NOT NULL,
    TRADE_DATE      DATE         NOT NULL,
    IS_OPEN         TINYINT(1)   NOT NULL DEFAULT 0,
    PRICES_SYNCED   TINYINT(1)   NOT NULL DEFAULT 0,
    PRIMARY KEY (EXCHANGE, TRADE_DATE)
) COMMENT='거래소 개장일';

-- 수동 수집 작업 (재조회 진행률/에러)
CREATE TABLE IF NOT EXISTS COLLECTION_TASK (
    ID            BIGINT       NOT NULL AUTO_INCREMENT,
    TYPE          VARCHAR(10)  NOT NULL COMMENT 'STOCK/PRICE/EVENT',
    SCOPE         VARCHAR(100) NOT NULL COMMENT '수집 범위 표시 문자열',
    EXCHANGE      VARCHAR(10)            COMMENT '대상 거래소 (PRICE만, STOCK/EVENT는 NULL)',
    FROM_DATE     DATE         NOT NULL COMMENT '수집 시작일 (재실행 파라미터)',
    TO_DATE       DATE         NOT NULL COMMENT '수집 종료일 (재실행 파라미터)',
    STATUS        VARCHAR(10)  NOT NULL COMMENT 'PENDING/RUNNING/DONE/FAILED',
    TOTAL         INT          NOT NULL DEFAULT 0,
    DONE          INT          NOT NULL DEFAULT 0,
    ADJUSTED_TOTAL INT         NOT NULL DEFAULT 0 COMMENT '수정주가 재조회 대상 종목 수 (0=없음)',
    ADJUSTED_DONE  INT         NOT NULL DEFAULT 0 COMMENT '수정주가 재조회 완료 종목 수',
    ERROR_CODE    VARCHAR(50),
    ERROR_DETAIL  VARCHAR(1000),
    REQUESTED_BY  BIGINT,
    CREATED_AT    DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    STARTED_AT    DATETIME(6),
    PROGRESS_AT   DATETIME(6) COMMENT '진행률 마지막 갱신 시각 (ETA 계산 기준)',
    FINISHED_AT   DATETIME(6),
    PRIMARY KEY (ID),
    INDEX IDX_CT_STATUS (STATUS),
    INDEX IDX_CT_CREATED_AT (CREATED_AT)
) COMMENT='수동 수집 작업';

-- 회원 (MemberProfile)
CREATE TABLE IF NOT EXISTS MEMBER (
    ID         BIGINT       NOT NULL AUTO_INCREMENT,
    EMAIL      VARCHAR(100) NOT NULL,
    NAME       VARCHAR(50)  NOT NULL,
    ROLE       VARCHAR(20)  NOT NULL COMMENT 'USER/ADMIN/ROOT',
    CREATED_AT DATETIME(6)  NOT NULL,
    PRIMARY KEY (ID)
) COMMENT='회원';

CREATE TABLE IF NOT EXISTS CREDENTIAL (
    MEMBER_ID               BIGINT       NOT NULL,
    USERNAME                VARCHAR(50)  NOT NULL,
    PASSWORD_HASH           VARCHAR(255) NOT NULL,
    LAST_LOGIN_AT           DATETIME(6),
    FAILED_ATTEMPTS         INT          NOT NULL,
    LOCKED_UNTIL            DATETIME(6),
    PASSWORD_RESET_REQUIRED TINYINT(1)   NOT NULL,
    PRIMARY KEY (MEMBER_ID),
    UNIQUE KEY UK_CREDENTIAL_USERNAME (USERNAME)
) COMMENT='자격증명';

CREATE TABLE IF NOT EXISTS INVITE_CODE (
    ID          BIGINT       NOT NULL AUTO_INCREMENT,
    VERSION     BIGINT       NOT NULL,
    CODE        VARCHAR(64)  NOT NULL,
    ROLE        VARCHAR(20)  NOT NULL,
    EXPIRES_AT  DATETIME(6)  NOT NULL,
    USED_AT     DATETIME(6),
    CREATED_BY  VARCHAR(50)  NOT NULL,
    CREATED_AT  DATETIME(6)  NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_INVITE_CODE (CODE)
) COMMENT='초대 코드';

CREATE TABLE IF NOT EXISTS MEMBER_FEATURE_GRANT (
    ID              BIGINT       NOT NULL AUTO_INCREMENT,
    MEMBER_ID       BIGINT       NOT NULL,
    FEATURE_CODE    VARCHAR(50)  NOT NULL,
    ACTIVE          TINYINT(1)   NOT NULL,
    GRANTED_AT      DATETIME(6)  NOT NULL,
    GRANTED_BY      BIGINT,
    UPDATED_AT      DATETIME(6)  NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_MEMBER_FEATURE_GRANT (MEMBER_ID, FEATURE_CODE),
    INDEX IDX_MEMBER_FEATURE_GRANT_MEMBER_ID (MEMBER_ID)
) COMMENT='기능 권한';

CREATE TABLE IF NOT EXISTS MEMBER_SUB_MENU_GRANT (
    ID              BIGINT       NOT NULL AUTO_INCREMENT,
    MEMBER_ID       BIGINT       NOT NULL,
    SUB_MENU_CODE   VARCHAR(50)  NOT NULL,
    ACTIVE          TINYINT(1)   NOT NULL,
    GRANTED_AT      DATETIME(6)  NOT NULL,
    GRANTED_BY      BIGINT,
    UPDATED_AT      DATETIME(6)  NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_MEMBER_SUB_MENU_GRANT (MEMBER_ID, SUB_MENU_CODE),
    INDEX IDX_MEMBER_SUB_MENU_GRANT_MEMBER_ID (MEMBER_ID)
) COMMENT='하위 메뉴 권한';

CREATE TABLE IF NOT EXISTS MEMBER_MODULE_DISPLAY (
    ID              BIGINT       NOT NULL AUTO_INCREMENT,
    MEMBER_ID       BIGINT       NOT NULL,
    MODULE_CODE     VARCHAR(50)  NOT NULL,
    DISPLAY_ORDER   INT          NOT NULL,
    HIDDEN          TINYINT(1)   NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_MEMBER_MODULE_DISPLAY (MEMBER_ID, MODULE_CODE),
    INDEX IDX_MEMBER_MODULE_DISPLAY_MEMBER_ID (MEMBER_ID)
) COMMENT='모듈 표시 순서';

CREATE TABLE IF NOT EXISTS MEMBER_FEATURE_DISPLAY (
    ID              BIGINT       NOT NULL AUTO_INCREMENT,
    MEMBER_ID       BIGINT       NOT NULL,
    FEATURE_CODE    VARCHAR(50)  NOT NULL,
    DISPLAY_ORDER   INT          NOT NULL,
    HIDDEN          TINYINT(1)   NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_MEMBER_FEATURE_DISPLAY (MEMBER_ID, FEATURE_CODE),
    INDEX IDX_MEMBER_FEATURE_DISPLAY_MEMBER_ID (MEMBER_ID)
) COMMENT='기능 표시 순서';

CREATE TABLE IF NOT EXISTS STOCK_FILTER (
    ID               BIGINT       NOT NULL AUTO_INCREMENT,
    MEMBER_ID        BIGINT,
    NAME             VARCHAR(100) NOT NULL,
    DESCRIPTION      VARCHAR(500),
    TAG_CONDITIONS   JSON         NOT NULL,
    STOCK_CONDITIONS JSON         NOT NULL,
    NUMERIC_CONDITIONS JSON       NOT NULL,
    ENABLED          TINYINT(1)   NOT NULL,
    DISPLAY_ORDER    INT          NOT NULL,
    CREATED_AT       DATETIME(6)  NOT NULL,
    UPDATED_AT       DATETIME(6)  NOT NULL,
    CREATED_BY       VARCHAR(50)  NOT NULL,
    UPDATED_BY       VARCHAR(50),
    PRIMARY KEY (ID),
    UNIQUE KEY UK_STOCK_FILTER_MEMBER_NAME (MEMBER_ID, NAME),
    INDEX IDX_STOCK_FILTER_OWNER (MEMBER_ID, ENABLED, DISPLAY_ORDER)
) COMMENT='종목 필터';

CREATE TABLE IF NOT EXISTS SEARCH_FILTER (
    ID              BIGINT       NOT NULL AUTO_INCREMENT,
    MEMBER_ID       BIGINT       NOT NULL,
    NAME            VARCHAR(100) NOT NULL,
    DATE_RULE       VARCHAR(20)  NOT NULL,
    MARKETS         JSON         NOT NULL,
    PRICE_TYPE      VARCHAR(10)  NOT NULL DEFAULT 'RAW' COMMENT '주가 유형 (RAW=비수정/ADJUSTED=수정)',
    EXPRESSION      TEXT         NOT NULL,
    STOCK_FILTER_ID BIGINT,
    DISPLAY_ORDER   INT          NOT NULL,
    CREATED_AT      DATETIME(6)  NOT NULL,
    UPDATED_AT      DATETIME(6)  NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_SEARCH_FILTER_MEMBER_NAME (MEMBER_ID, NAME),
    INDEX IDX_SEARCH_FILTER_MEMBER_ID (MEMBER_ID),
    INDEX IDX_SEARCH_FILTER_SF_ID (STOCK_FILTER_ID)
) COMMENT='검색 필터';

CREATE TABLE IF NOT EXISTS INDICATOR_PRESET (
    ID              BIGINT       NOT NULL AUTO_INCREMENT,
    MEMBER_ID       BIGINT       NOT NULL,
    NAME            VARCHAR(100) NOT NULL,
    ITEMS           JSON         NOT NULL,
    PANEL_ORDER     JSON,
    DISPLAY_ORDER   INT          NOT NULL,
    CREATED_AT      DATETIME(6)  NOT NULL,
    UPDATED_AT      DATETIME(6)  NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_INDICATOR_PRESET_MEMBER_NAME (MEMBER_ID, NAME),
    INDEX IDX_INDICATOR_PRESET_MEMBER_ID (MEMBER_ID)
) COMMENT='지표 프리셋';

CREATE TABLE IF NOT EXISTS INVESTOR_DAILY (
    EXCHANGE         VARCHAR(15)  NOT NULL COMMENT 'KOSPI/KOSDAQ/KONEX/NXT/INTEGRATED',
    STOCK_CODE       VARCHAR(20)  NOT NULL,
    TRADE_DATE       DATE         NOT NULL,
    INDIVIDUAL_BUY   BIGINT       NOT NULL,
    INDIVIDUAL_SELL  BIGINT       NOT NULL,
    INSTITUTION_BUY  BIGINT       NOT NULL,
    INSTITUTION_SELL BIGINT       NOT NULL,
    FOREIGN_BUY      BIGINT       NOT NULL,
    FOREIGN_SELL     BIGINT       NOT NULL,
    PRIMARY KEY (EXCHANGE, STOCK_CODE, TRADE_DATE)
) COMMENT='투자자 매매동향';

CREATE TABLE IF NOT EXISTS SYSTEM_EVENT (
    ID          BIGINT       NOT NULL AUTO_INCREMENT,
    EVENT_TYPE  VARCHAR(50)  NOT NULL,
    MARKET_TYPE VARCHAR(10),
    OCCURRED_AT DATETIME(6)  NOT NULL,
    DETAIL      JSON         NOT NULL,
    PRIMARY KEY (ID),
    INDEX IDX_SYSTEM_EVENT_OCCURRED_AT (OCCURRED_AT),
    INDEX IDX_SYSTEM_EVENT_TYPE (EVENT_TYPE)
) COMMENT='운영 이벤트';
