-- DOVE-LAB schema v2 (2026-05-30)

CREATE TABLE IF NOT EXISTS STOCK (
    TICKER              VARCHAR(20)  NOT NULL COMMENT '종목코드',
    ISIN                VARCHAR(12)           COMMENT 'ISIN',
    MARKET              VARCHAR(10)  NOT NULL COMMENT 'KOSPI/KOSDAQ/KONEX',
    LISTING_DATE        DATE,
    SECUGRP_NM          VARCHAR(40),
    KIND_STKCERT_TP_NM  VARCHAR(40),
    CORP_CODE           VARCHAR(8)            COMMENT 'DART 고유번호(재무 조회 키)',
    CREATED_AT          DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (TICKER),
    INDEX IDX_STOCK_ISIN (ISIN),
    INDEX IDX_STOCK_SECUGRP (SECUGRP_NM),
    INDEX IDX_STOCK_STKCERT (KIND_STKCERT_TP_NM),
    INDEX IDX_STOCK_MARKET (MARKET),
    INDEX IDX_STOCK_CORP_CODE (CORP_CODE)
) COMMENT='종목 마스터';

CREATE TABLE IF NOT EXISTS STOCK_DETAIL (
    TICKER              VARCHAR(20)  NOT NULL,
    LISTED_SHARES       BIGINT,
    CAPITAL_AMOUNT      BIGINT,
    FACE_VALUE          BIGINT,
    STOCK_KIND_CD       VARCHAR(3),
    ETF_DVSN_CD         VARCHAR(2),
    REITS_KIND_CD       VARCHAR(1),
    KOSPI200_ITEM_YN    VARCHAR(1),
    IDX_BZTP_LCLS_CD    VARCHAR(3),
    IDX_BZTP_MCLS_CD    VARCHAR(3),
    IDX_BZTP_SCLS_CD    VARCHAR(3),
    IDX_BZTP_LCLS_NM    VARCHAR(60),
    IDX_BZTP_MCLS_NM    VARCHAR(60),
    IDX_BZTP_SCLS_NM    VARCHAR(60),
    STD_IDST_CLSF_CD    VARCHAR(6),
    STD_IDST_CLSF_NM    VARCHAR(130),
    FRNR_PSNL_LMT_RT    VARCHAR(24),
    TR_STOP_YN          VARCHAR(1),
    ADMN_ITEM_YN        VARCHAR(1),
    LSTG_ABOL_DT        VARCHAR(8),
    SCTS_MKET_LSTG_DT   VARCHAR(8),
    PRDT_NAME           VARCHAR(60),
    PRDT_ABRV_NAME      VARCHAR(60),
    PRDT_ENG_NAME       VARCHAR(60),
    SHTN_PDNO           VARCHAR(12),
    PRDT_RISK_GRAD_CD   VARCHAR(2),
    PRDT_CLSF_CD        VARCHAR(6),
    PRDT_CLSF_NM        VARCHAR(60),
    UPDATED_AT          DATETIME(6)  NOT NULL,
    PRIMARY KEY (TICKER),
    INDEX IDX_SD_PRDT_CLSF (PRDT_CLSF_CD),
    INDEX IDX_SD_BZTP_LCLS (IDX_BZTP_LCLS_NM),
    INDEX IDX_SD_BZTP_MCLS (IDX_BZTP_MCLS_NM),
    INDEX IDX_SD_BZTP_SCLS (IDX_BZTP_SCLS_NM),
    INDEX IDX_SD_STD_IDST (STD_IDST_CLSF_NM),
    INDEX IDX_SD_PRDT_CLSF_NM (PRDT_CLSF_NM)
) COMMENT='종목 상세';

CREATE TABLE IF NOT EXISTS STOCK_TAG_VALUE (
    ID          BIGINT       NOT NULL AUTO_INCREMENT,
    FIELD       VARCHAR(20)  NOT NULL COMMENT '분류 차원 (TagField 이름)',
    TAG_VALUE   VARCHAR(130) NOT NULL COMMENT 'KRX/KIS 분류 값 원문',
    LABEL       VARCHAR(130) NOT NULL COMMENT '화면 표시명 (기본=원문값)',
    CREATED_AT  DATETIME(6)  NOT NULL,
    UPDATED_AT  DATETIME(6)  NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_STV_FIELD_VALUE (FIELD, TAG_VALUE),
    INDEX IDX_STV_FIELD (FIELD)
) COMMENT='종목 분류 값 마스터 (수집 시 자동 등록, 표시명 편집)';

CREATE TABLE IF NOT EXISTS STOCK_EVENT (
    ID          BIGINT       NOT NULL AUTO_INCREMENT,
    TICKER      VARCHAR(20)  NOT NULL COMMENT '종목코드',
    EVENT_TYPE  VARCHAR(20)  NOT NULL COMMENT '이벤트 유형 (StockEventType)',
    EVENT_DATE  DATE         NOT NULL COMMENT '이벤트 기준일 (KSD record_date)',
    SUMMARY     VARCHAR(200) COMMENT '표시용 요약',
    DETAIL      TEXT         COMMENT 'KSD 원본 응답 JSON',
    SOURCE      VARCHAR(20)  COMMENT '수집 출처 (예: KIS_KSD)',
    CREATED_AT  DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ID),
    UNIQUE KEY UK_SE_TICKER_TYPE_DATE (TICKER, EVENT_TYPE, EVENT_DATE),
    INDEX IDX_SE_TICKER_DATE (TICKER, EVENT_DATE),
    INDEX IDX_SE_EVENT_DATE (EVENT_DATE)
) COMMENT='종목 권리 이벤트 (배당·증자·감자·합병/분할·액면, KIS 예탁원정보)';

CREATE TABLE IF NOT EXISTS STOCK_PRICE (
    TICKER      VARCHAR(20)  NOT NULL,
    EXCHANGE    TINYINT      NOT NULL COMMENT '거래소 코드(KOSPI/KOSDAQ/KONEX/NXT/INTEGRATED)',
    PRICE_TYPE  TINYINT      NOT NULL COMMENT '가격유형 코드(RAW/ADJUSTED)',
    TRADE_DATE  DATE         NOT NULL,
    OPEN_PRICE  BIGINT,
    HIGH_PRICE  BIGINT,
    LOW_PRICE   BIGINT,
    CLOSE_PRICE BIGINT,
    VOLUME      BIGINT,
    TURNOVER    BIGINT,
    PRIMARY KEY (TICKER, EXCHANGE, PRICE_TYPE, TRADE_DATE),
    INDEX IDX_SP_TICKER_DATE (TICKER, TRADE_DATE),
    INDEX IDX_SP_EXCHANGE_DATE (EXCHANGE, TRADE_DATE),
    INDEX IDX_SP_EXCHANGE_PT_DATE (EXCHANGE, PRICE_TYPE, TRADE_DATE)
) COMMENT='일별 주가';

CREATE TABLE IF NOT EXISTS STOCK_FEATURE_DAILY (
    TICKER            VARCHAR(20)  NOT NULL,
    EXCHANGE          TINYINT      NOT NULL COMMENT '거래소 코드',
    PRICE_TYPE        TINYINT      NOT NULL COMMENT '가격유형 코드',
    TRADE_DATE        DATE         NOT NULL,
    SEQ               INT          NOT NULL COMMENT '그룹 내 거래일 순번(전일·미래수익 비교용)',
    OPEN_PRICE        BIGINT,
    HIGH_PRICE        BIGINT,
    LOW_PRICE         BIGINT,
    CLOSE_PRICE       BIGINT,
    VOLUME            BIGINT,
    TURNOVER          BIGINT,
    SMA_5             FLOAT,
    SMA_10            FLOAT,
    SMA_20            FLOAT,
    SMA_50            FLOAT,
    SMA_60            FLOAT,
    SMA_120           FLOAT,
    SMA_200           FLOAT,
    EMA_5             FLOAT,
    EMA_10            FLOAT,
    EMA_20            FLOAT,
    EMA_60            FLOAT,
    EMA_120           FLOAT,
    EMA_200           FLOAT,
    RSI_9             FLOAT,
    RSI_14            FLOAT,
    RSI_21            FLOAT,
    MACD_LINE         FLOAT,
    MACD_SIGNAL       FLOAT,
    MACD_HISTOGRAM    FLOAT,
    STOCHASTIC_K_14_7 FLOAT,
    STOCHASTIC_D_14_7 FLOAT,
    ADX_14            FLOAT,
    PLUS_DI_14        FLOAT,
    MINUS_DI_14       FLOAT,
    VOLUME_RATIO_20   FLOAT,
    OBV               FLOAT,
    BB_UPPER_20       FLOAT,
    BB_MIDDLE_20      FLOAT,
    BB_LOWER_20       FLOAT,
    BB_PERCENT_B_20   FLOAT,
    BB_WIDTH_20       FLOAT,
    ATR               FLOAT,
    MFI               FLOAT,
    CCI               FLOAT,
    WILLIAMS_R        FLOAT,
    VOLATILITY_5D     FLOAT,
    VOLATILITY_20D    FLOAT,
    HIGH_20D_RATIO    FLOAT,
    HIGH_52W_RATIO    FLOAT,
    LOW_20D_RATIO     FLOAT,
    VOLUME_MA20_RATIO FLOAT,
    GAP_OPEN          FLOAT,
    RET_1D            FLOAT,
    RET_5D            FLOAT,
    RET_10D           FLOAT,
    BODY_RATIO        FLOAT,
    LOWER_WICK        FLOAT,
    UPPER_WICK_RATIO  FLOAT        COMMENT '윗꼬리 비율 (고가-max(시가,종가))/(고가-저가)',
    CLOSE_POS         FLOAT        COMMENT '당일 범위 내 종가 위치 (종가-저가)/(고가-저가)',
    BULLISH_ENGULFING FLOAT        COMMENT '상승 장악형 캔들 여부(1/0)',
    BEARISH_ENGULFING FLOAT        COMMENT '하락 장악형 캔들 여부(1/0)',
    BREAKOUT_20D      FLOAT        COMMENT '직전 20일 고점 상향 돌파 여부(1/0)',
    IS_52W_HIGH       TINYINT,
    IS_52W_LOW        TINYINT,
    IS_20D_HIGH       TINYINT,
    IS_20D_LOW        TINYINT,
    CALCULATED_AT     DATETIME(6)  NOT NULL,
    PRIMARY KEY (TICKER, EXCHANGE, PRICE_TYPE, TRADE_DATE),
    INDEX IDX_SFD_EXCHANGE_DATE (EXCHANGE, PRICE_TYPE, TRADE_DATE),
    INDEX IDX_SFD_SEQ (TICKER, EXCHANGE, PRICE_TYPE, SEQ)
) COMMENT='종목·거래일별 지표(wide)' ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE IF NOT EXISTS INDICATOR_CURSOR (
    ID              BIGINT       NOT NULL AUTO_INCREMENT,
    TICKER          VARCHAR(20)  NOT NULL,
    EXCHANGE        TINYINT      NOT NULL COMMENT '거래소 코드',
    PRICE_TYPE      TINYINT      NOT NULL COMMENT '가격유형 코드',
    CURSOR_DATE     DATE         COMMENT 'NULL=1985-01-01부터',
    UPDATED_AT      DATETIME(6)  NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_IC (TICKER, EXCHANGE, PRICE_TYPE),
    INDEX IDX_IC_TICKER (TICKER)
) COMMENT='지표 계산 커서(그룹 단위)';

CREATE TABLE IF NOT EXISTS STOCK_RANK_DAILY (
    TICKER               VARCHAR(20)  NOT NULL,
    EXCHANGE             TINYINT      NOT NULL COMMENT '거래소 코드',
    PRICE_TYPE           TINYINT      NOT NULL COMMENT '가격유형 코드',
    TRADE_DATE           DATE         NOT NULL,
    RANK_RET_1D          FLOAT        COMMENT '1일 수익률 횡단면 percentile(0~1)',
    RANK_RET_5D          FLOAT        COMMENT '5일 수익률 횡단면 percentile(0~1)',
    RANK_RET_10D         FLOAT        COMMENT '10일 수익률 횡단면 percentile(0~1)',
    RANK_VOLUME_RATIO_20 FLOAT        COMMENT '20일 거래량비율 횡단면 percentile(0~1)',
    RANK_RSI_14          FLOAT        COMMENT 'RSI(14) 횡단면 percentile(0~1)',
    RANK_MACD_HISTOGRAM  FLOAT        COMMENT 'MACD 히스토그램 횡단면 percentile(0~1)',
    RANK_HIGH_52W_RATIO  FLOAT        COMMENT '52주 고가대비비율 횡단면 percentile(0~1)',
    RANK_VOLATILITY_20D  FLOAT        COMMENT '20일 변동성 횡단면 percentile(0~1)',
    RANK_TURNOVER        FLOAT        COMMENT '거래대금 횡단면 percentile(0~1)',
    CALCULATED_AT        DATETIME(6)  NOT NULL,
    PRIMARY KEY (TICKER, EXCHANGE, PRICE_TYPE, TRADE_DATE),
    INDEX IDX_SRD_EXCHANGE_DATE (EXCHANGE, PRICE_TYPE, TRADE_DATE),
    INDEX IDX_SRD_TICKER_DATE (TICKER, EXCHANGE, PRICE_TYPE, TRADE_DATE)
) COMMENT='종목·거래일별 횡단면 순위(wide)' ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE IF NOT EXISTS RANK_CURSOR (
    ID           BIGINT       NOT NULL AUTO_INCREMENT,
    UNIVERSE     TINYINT      NOT NULL COMMENT 'universe 코드(KRX/KONEX)',
    PRICE_TYPE   TINYINT      NOT NULL COMMENT '가격유형 코드',
    CURSOR_DATE  DATE         COMMENT '순위 계산이 완료된 마지막 거래일. NULL=처음부터',
    UPDATED_AT   DATETIME(6)  NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_RC_UNIVERSE_PRICETYPE (UNIVERSE, PRICE_TYPE)
) COMMENT='횡단면 순위 계산 커서(universe·가격유형 단위)';

CREATE TABLE IF NOT EXISTS CUSTOM_METRIC_DEF (
    ID                 BIGINT       NOT NULL AUTO_INCREMENT,
    NAME               VARCHAR(100) NOT NULL COMMENT '지표 이름(고유)',
    DESCRIPTION        VARCHAR(500) COMMENT '설명',
    SHAPE              VARCHAR(10)  NOT NULL COMMENT '출력 모양(SERIES=시장 스칼라/PANEL=종목별)',
    SPEC               TEXT         NOT NULL COMMENT '계산식 DSL(JSON 트리)',
    PRICE_TYPE         VARCHAR(10)  NOT NULL COMMENT '피처 주가 유형(RAW/ADJUSTED)',
    ACTIVE             TINYINT(1)   NOT NULL COMMENT '활성 여부(0=야간 계산 스킵·숨김)',
    LAST_COMPUTED_DATE DATE         COMMENT '마지막 계산·저장 거래일. NULL=미계산',
    LAST_ERROR         VARCHAR(500) COMMENT '마지막 계산 오류. NULL=정상',
    CREATED_BY         VARCHAR(50)  NOT NULL COMMENT '생성자 username',
    CREATED_AT         DATETIME(6)  NOT NULL,
    UPDATED_AT         DATETIME(6)  NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_CMD_NAME (NAME)
) COMMENT='커스텀 지표 정의(ROOT 계산식 DSL + 상태)';

CREATE TABLE IF NOT EXISTS CUSTOM_METRIC_DAILY (
    METRIC_ID     BIGINT       NOT NULL COMMENT '지표 ID',
    TRADE_DATE    DATE         NOT NULL,
    VALUE         DOUBLE       NOT NULL COMMENT '지표 계산값',
    CALCULATED_AT DATETIME(6)  NOT NULL,
    PRIMARY KEY (METRIC_ID, TRADE_DATE)
) COMMENT='커스텀 지표(SERIES) 거래일별 계산값(시장 단일 스칼라)';

CREATE TABLE IF NOT EXISTS ML_MODEL (
    ID               BIGINT       NOT NULL AUTO_INCREMENT,
    NAME             VARCHAR(100) NOT NULL COMMENT '모델 이름(예: swing_entry)',
    VERSION          VARCHAR(50)  NOT NULL COMMENT '버전(예: 1.0.0)',
    ARTIFACT         LONGBLOB     NOT NULL COMMENT '모델 파일(joblib pickle: model·calibrator·meta)',
    META_JSON        LONGTEXT     NOT NULL COMMENT 'meta.json 원본(features 목록·entry_zone·feature_hash 포함)',
    OUTPUT_TYPE      VARCHAR(20)  NOT NULL COMMENT '출력 의미(PROBABILITY/REGRESSION)',
    SCORE_EXCHANGES  VARCHAR(40)  NOT NULL COMMENT '채점 대상 거래소 코드 CSV(예: 0,1)',
    SCORE_PRICE_TYPE TINYINT      NOT NULL COMMENT '채점 대상 주가유형 코드(기본 ADJUSTED)',
    STATUS           VARCHAR(20)  NOT NULL COMMENT '채점 활성 상태(ACTIVE/INACTIVE)',
    SCORE_CURSOR     DATE                  COMMENT '마지막으로 채점 완료된 거래일. NULL이면 미시작',
    LAST_SCORED_AT   DATETIME(6)           COMMENT '마지막 채점 성공 일시',
    LAST_ERROR       VARCHAR(500)          COMMENT '마지막 채점 실패 사유(코드:메시지). 성공 시 NULL',
    CREATED_BY       VARCHAR(100) NOT NULL COMMENT '등록자',
    CREATED_AT       DATETIME     NOT NULL COMMENT '생성 일시',
    UPDATED_AT       DATETIME     NOT NULL COMMENT '최종 갱신 일시',
    PRIMARY KEY (ID),
    INDEX IDX_MM_STATUS (STATUS),
    INDEX IDX_MM_NAME_VERSION (NAME, VERSION)
) COMMENT='등록된 ML 모델 레지스트리';

CREATE TABLE IF NOT EXISTS STOCK_MODEL_SCORE (
    TICKER      VARCHAR(20) NOT NULL,
    EXCHANGE    TINYINT     NOT NULL COMMENT '거래소 코드',
    PRICE_TYPE  TINYINT     NOT NULL COMMENT '가격유형 코드',
    TRADE_DATE  DATE        NOT NULL,
    MODEL_ID    BIGINT      NOT NULL COMMENT '모델 ID(ML_MODEL.ID)',
    SCORE       FLOAT       NOT NULL COMMENT '모델 출력값(0~1 보정 확률 또는 연속값)',
    SCORED_AT   DATETIME    NOT NULL COMMENT '채점 일시',
    PRIMARY KEY (TICKER, EXCHANGE, PRICE_TYPE, TRADE_DATE, MODEL_ID),
    INDEX IDX_SMS_CHART (TICKER, EXCHANGE, PRICE_TYPE, MODEL_ID, TRADE_DATE),
    INDEX IDX_SMS_SEARCH (TRADE_DATE, MODEL_ID, SCORE)
) COMMENT='종목·거래일·모델별 채점 점수' ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

CREATE TABLE IF NOT EXISTS EXCHANGE_TRADING_DATE (
    EXCHANGE        VARCHAR(10)  NOT NULL,
    TRADE_DATE      DATE         NOT NULL,
    PRICES_SYNCED   TINYINT(1)   NOT NULL DEFAULT 0,
    PRIMARY KEY (EXCHANGE, TRADE_DATE)
) COMMENT='거래소 개장일';

-- 수동 수집 작업 (재조회 진행률/에러)
CREATE TABLE IF NOT EXISTS COLLECTION_TASK (
    ID            BIGINT       NOT NULL AUTO_INCREMENT,
    TYPE          VARCHAR(20)  NOT NULL COMMENT 'STOCK_SYNC/STOCK_DETAIL/PRICE/EVENT/INVESTOR',
    SCOPE         VARCHAR(100) NOT NULL COMMENT '수집 범위 표시 문자열',
    EXCHANGE      VARCHAR(10)            COMMENT '대상 거래소 (PRICE만, STOCK/EVENT는 NULL)',
    FROM_DATE     DATE         NOT NULL COMMENT '수집 시작일 (재실행 파라미터)',
    TO_DATE       DATE         NOT NULL COMMENT '수집 종료일 (재실행 파라미터)',
    STATUS        VARCHAR(10)  NOT NULL COMMENT 'PENDING/RUNNING/DONE/FAILED',
    TOTAL         INT          NOT NULL DEFAULT 0,
    DONE          INT          NOT NULL DEFAULT 0,
    ADJUSTED_FROM  DATE                  COMMENT '수정주가 재조회 시작일 (NULL=재조회 생략)',
    ADJUSTED_TOTAL INT         NOT NULL DEFAULT 0 COMMENT '수정주가 재조회 대상 종목 수 (0=없음)',
    ADJUSTED_DONE  INT         NOT NULL DEFAULT 0 COMMENT '수정주가 재조회 완료 종목 수',
    ERROR_CODE    VARCHAR(50),
    ERROR_DETAIL  VARCHAR(1000),
    REQUESTED_BY  BIGINT,
    CREATED_AT    DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    STARTED_AT    DATETIME(6),
    PROGRESS_AT   DATETIME(6) COMMENT '진행률 마지막 갱신 시각 (ETA 계산 기준)',
    FINISHED_AT   DATETIME(6),
    PRIMARY KEY (ID),
    INDEX IDX_CT_STATUS (STATUS),
    INDEX IDX_CT_CREATED_AT (CREATED_AT)
) COMMENT='수동 수집 작업';

-- 회원 (MemberProfile)
CREATE TABLE IF NOT EXISTS MEMBER (
    ID         BIGINT       NOT NULL AUTO_INCREMENT,
    EMAIL      VARCHAR(100) NOT NULL,
    NAME       VARCHAR(50)  NOT NULL,
    ROLE       VARCHAR(20)  NOT NULL COMMENT 'USER/ADMIN/ROOT',
    CREATED_AT DATETIME(6)  NOT NULL,
    PRIMARY KEY (ID)
) COMMENT='회원';

CREATE TABLE IF NOT EXISTS CREDENTIAL (
    MEMBER_ID               BIGINT       NOT NULL,
    USERNAME                VARCHAR(50)  NOT NULL,
    PASSWORD_HASH           VARCHAR(255) NOT NULL,
    LAST_LOGIN_AT           DATETIME(6),
    FAILED_ATTEMPTS         INT          NOT NULL,
    LOCKED_UNTIL            DATETIME(6),
    PASSWORD_RESET_REQUIRED TINYINT(1)   NOT NULL,
    PRIMARY KEY (MEMBER_ID),
    UNIQUE KEY UK_CREDENTIAL_USERNAME (USERNAME)
) COMMENT='자격증명';

CREATE TABLE IF NOT EXISTS INVITE_CODE (
    ID          BIGINT       NOT NULL AUTO_INCREMENT,
    VERSION     BIGINT       NOT NULL,
    CODE        VARCHAR(64)  NOT NULL,
    ROLE        VARCHAR(20)  NOT NULL,
    EXPIRES_AT  DATETIME(6)  NOT NULL,
    USED_AT     DATETIME(6),
    CREATED_BY  VARCHAR(50)  NOT NULL,
    CREATED_AT  DATETIME(6)  NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_INVITE_CODE (CODE)
) COMMENT='초대 코드';

CREATE TABLE IF NOT EXISTS MEMBER_CAPABILITY_GRANT (
    ID              BIGINT       NOT NULL AUTO_INCREMENT,
    MEMBER_ID       BIGINT       NOT NULL,
    CAPABILITY      VARCHAR(50)  NOT NULL,
    GRANTED_AT      DATETIME(6)  NOT NULL,
    GRANTED_BY      BIGINT,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_MEMBER_CAPABILITY_GRANT (MEMBER_ID, CAPABILITY),
    INDEX IDX_MEMBER_CAPABILITY_GRANT_MEMBER_ID (MEMBER_ID)
) COMMENT='capability 권한';

CREATE TABLE IF NOT EXISTS MEMBER_CUSTOM_INDICATOR_GRANT (
    ID          BIGINT       NOT NULL AUTO_INCREMENT,
    MEMBER_ID   BIGINT       NOT NULL COMMENT '회원 ID',
    METRIC_ID   BIGINT       NOT NULL COMMENT '커스텀 지표 ID',
    GRANTED_AT  DATETIME(6)  NOT NULL COMMENT '부여 일시',
    GRANTED_BY  BIGINT       COMMENT '부여한 관리자 회원 ID (null=시스템)',
    PRIMARY KEY (ID),
    UNIQUE KEY UK_MEMBER_CUSTOM_INDICATOR_GRANT (MEMBER_ID, METRIC_ID),
    INDEX IDX_MCIG_MEMBER_ID (MEMBER_ID),
    INDEX IDX_MCIG_METRIC_ID (METRIC_ID)
) COMMENT='사용자별 커스텀 지표 접근 권한';

CREATE TABLE IF NOT EXISTS MEMBER_MODEL_GRANT (
    ID          BIGINT       NOT NULL AUTO_INCREMENT,
    MEMBER_ID   BIGINT       NOT NULL COMMENT '회원 ID',
    MODEL_ID    BIGINT       NOT NULL COMMENT '모델 ID',
    GRANTED_AT  DATETIME(6)  NOT NULL COMMENT '부여 일시',
    GRANTED_BY  BIGINT       COMMENT '부여한 관리자 회원 ID (null=시스템)',
    PRIMARY KEY (ID),
    UNIQUE KEY UK_MEMBER_MODEL_GRANT (MEMBER_ID, MODEL_ID),
    INDEX IDX_MMG_MEMBER_ID (MEMBER_ID),
    INDEX IDX_MMG_MODEL_ID (MODEL_ID)
) COMMENT='사용자별 모델 점수 접근 권한';

CREATE TABLE IF NOT EXISTS STOCK_FILTER (
    ID               BIGINT       NOT NULL AUTO_INCREMENT,
    MEMBER_ID        BIGINT,
    NAME             VARCHAR(100) NOT NULL,
    DESCRIPTION      VARCHAR(500),
    TAG_CONDITIONS   JSON         NOT NULL,
    STOCK_CONDITIONS JSON         NOT NULL,
    NUMERIC_CONDITIONS JSON       NOT NULL,
    NAME_PATTERN_CONDITIONS JSON  NOT NULL,
    ENABLED          TINYINT(1)   NOT NULL,
    DISPLAY_ORDER    INT          NOT NULL,
    CREATED_AT       DATETIME(6)  NOT NULL,
    UPDATED_AT       DATETIME(6)  NOT NULL,
    CREATED_BY       VARCHAR(50)  NOT NULL,
    UPDATED_BY       VARCHAR(50),
    PRIMARY KEY (ID),
    UNIQUE KEY UK_STOCK_FILTER_MEMBER_NAME (MEMBER_ID, NAME),
    INDEX IDX_STOCK_FILTER_OWNER (MEMBER_ID, ENABLED, DISPLAY_ORDER)
) COMMENT='종목 필터';

CREATE TABLE IF NOT EXISTS SEARCH_FILTER (
    ID              BIGINT       NOT NULL AUTO_INCREMENT,
    MEMBER_ID       BIGINT       NOT NULL,
    NAME            VARCHAR(100) NOT NULL,
    DATE_RULE       VARCHAR(20)  NOT NULL,
    MARKETS         JSON         NOT NULL,
    PRICE_TYPE      VARCHAR(10)  NOT NULL DEFAULT 'RAW' COMMENT '주가 유형 (RAW=비수정/ADJUSTED=수정)',
    EXCHANGE        VARCHAR(20)  NOT NULL DEFAULT 'KRX' COMMENT '지표 데이터 거래소 (KRX/NXT/INTEGRATED)',
    EXPRESSION      TEXT         NOT NULL,
    PIPELINE        TEXT         COMMENT '순서 단계 목록(JSON, null=단순 필터)',
    STOCK_FILTER_ID BIGINT,
    DISPLAY_ORDER   INT          NOT NULL,
    CREATED_AT      DATETIME(6)  NOT NULL,
    UPDATED_AT      DATETIME(6)  NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_SEARCH_FILTER_MEMBER_NAME (MEMBER_ID, NAME),
    INDEX IDX_SEARCH_FILTER_MEMBER_ID (MEMBER_ID),
    INDEX IDX_SEARCH_FILTER_SF_ID (STOCK_FILTER_ID)
) COMMENT='검색 필터';

CREATE TABLE IF NOT EXISTS INDICATOR_PRESET (
    ID              BIGINT       NOT NULL AUTO_INCREMENT,
    MEMBER_ID       BIGINT       NOT NULL,
    NAME            VARCHAR(100) NOT NULL,
    ITEMS           JSON         NOT NULL,
    PANEL_ORDER     JSON,
    OVERLAY         JSON         NULL,
    DISPLAY_ORDER   INT          NOT NULL,
    CREATED_AT      DATETIME(6)  NOT NULL,
    UPDATED_AT      DATETIME(6)  NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_INDICATOR_PRESET_MEMBER_NAME (MEMBER_ID, NAME),
    INDEX IDX_INDICATOR_PRESET_MEMBER_ID (MEMBER_ID)
) COMMENT='지표 프리셋';

CREATE TABLE IF NOT EXISTS INVESTOR_DAILY (
    STOCK_CODE       VARCHAR(20)  NOT NULL,
    TRADE_DATE       DATE         NOT NULL,
    INDIVIDUAL_BUY   BIGINT       NOT NULL,
    INDIVIDUAL_SELL  BIGINT       NOT NULL,
    INSTITUTION_BUY  BIGINT       NOT NULL,
    INSTITUTION_SELL BIGINT       NOT NULL,
    FOREIGN_BUY      BIGINT       NOT NULL,
    FOREIGN_SELL     BIGINT       NOT NULL,
    PRIMARY KEY (STOCK_CODE, TRADE_DATE),
    INDEX IDX_INVESTOR_DAILY_DATE (TRADE_DATE)
) COMMENT='투자자 매매동향 (KIS FHKST01010900 통합 집계)';

CREATE TABLE IF NOT EXISTS SYSTEM_EVENT (
    ID          BIGINT       NOT NULL AUTO_INCREMENT,
    EVENT_TYPE  VARCHAR(50)  NOT NULL,
    MARKET_TYPE VARCHAR(10),
    OCCURRED_AT DATETIME(6)  NOT NULL,
    DETAIL      JSON         NOT NULL,
    PRIMARY KEY (ID),
    INDEX IDX_SYSTEM_EVENT_OCCURRED_AT (OCCURRED_AT),
    INDEX IDX_SYSTEM_EVENT_TYPE (EVENT_TYPE)
) COMMENT='운영 이벤트';

-- DART 재무제표 원자료(공시 단위). 원본1+정정N을 접수번호로 각각 보존. 표준계정코드 기준 컬럼 매핑.
CREATE TABLE IF NOT EXISTS STOCK_FUNDAMENTAL (
    RCEPT_NO             VARCHAR(14)  NOT NULL COMMENT 'DART 접수번호(공시 고유)',
    FS_DIV               VARCHAR(3)   NOT NULL COMMENT '재무구분 CFS(연결)/OFS(별도)',
    TICKER               VARCHAR(20)  NOT NULL COMMENT '종목코드',
    CORP_CODE            VARCHAR(8)   NOT NULL COMMENT 'DART 고유번호',
    FISCAL_YEAR          SMALLINT     NOT NULL COMMENT '회계연도',
    REPORT_CODE          VARCHAR(5)   NOT NULL COMMENT '보고서(11011사업/11012반기/11013·11014분기)',
    RCEPT_DT             DATE         NOT NULL COMMENT '공시일(PIT 기준)',
    IS_AMENDMENT         TINYINT(1)   NOT NULL DEFAULT 0 COMMENT '정정 여부',
    REVENUE              BIGINT                COMMENT '매출액(ifrs-full_Revenue)',
    COST_OF_SALES        BIGINT                COMMENT '매출원가(ifrs-full_CostOfSales)',
    GROSS_PROFIT         BIGINT                COMMENT '매출총이익(ifrs-full_GrossProfit)',
    OPERATING_INCOME     BIGINT                COMMENT '영업이익(dart_OperatingIncomeLoss)',
    PROFIT_BEFORE_TAX    BIGINT                COMMENT '법인세차감전순이익(ifrs-full_ProfitLossBeforeTax)',
    NET_INCOME           BIGINT                COMMENT '당기순이익(ifrs-full_ProfitLoss)',
    NET_INCOME_CTRL      BIGINT                COMMENT '지배기업소유주순이익',
    TOTAL_ASSET          BIGINT                COMMENT '자산총계(ifrs-full_Assets)',
    CURRENT_ASSET        BIGINT                COMMENT '유동자산',
    NONCURRENT_ASSET     BIGINT                COMMENT '비유동자산',
    CASH_AND_EQUIV       BIGINT                COMMENT '현금및현금성자산',
    INVENTORIES          BIGINT                COMMENT '재고자산',
    TOTAL_LIABILITY      BIGINT                COMMENT '부채총계(ifrs-full_Liabilities)',
    CURRENT_LIABILITY    BIGINT                COMMENT '유동부채',
    TOTAL_EQUITY         BIGINT                COMMENT '자본총계(ifrs-full_Equity)',
    EQUITY_CTRL          BIGINT                COMMENT '지배기업소유주지분',
    ISSUED_CAPITAL       BIGINT                COMMENT '자본금(ifrs-full_IssuedCapital)',
    CF_OPERATING         BIGINT                COMMENT '영업활동현금흐름',
    CF_INVESTING         BIGINT                COMMENT '투자활동현금흐름',
    CF_FINANCING         BIGINT                COMMENT '재무활동현금흐름',
    COMMON_SHARES        BIGINT                COMMENT '보통주 상장주식수(stockTotqySttus)',
    CREATED_AT           DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (RCEPT_NO, FS_DIV),
    INDEX IDX_FUND_TICKER_PERIOD (TICKER, FISCAL_YEAR, REPORT_CODE),
    INDEX IDX_FUND_TICKER_RCEPT (TICKER, RCEPT_DT),
    INDEX IDX_FUND_AMEND_RCEPT (IS_AMENDMENT, RCEPT_DT)
) COMMENT='DART 재무제표 원자료(공시단위·표준계정)' ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

-- 일별 밸류에이션(미리계산). 실제(RAW) 종가 × PIT 최신 재무로 시총·4비율 산출 → 아무 날이나 스크리닝은 조회.
CREATE TABLE IF NOT EXISTS STOCK_VALUATION_DAILY (
    TICKER          VARCHAR(20)  NOT NULL COMMENT '종목코드',
    TRADE_DATE      DATE         NOT NULL COMMENT '거래일',
    CLOSE_PRICE     BIGINT                COMMENT '실제(RAW) 종가',
    MARKET_CAP      BIGINT                COMMENT '시가총액(RAW종가×KRX상장주식수 as-of)',
    PER             DOUBLE                COMMENT '시총/당기순이익(TTM,지배주주)',
    PBR             DOUBLE                COMMENT '시총/자본(지배주주지분)',
    PSR             DOUBLE                COMMENT '시총/매출액(TTM)',
    GPA             DOUBLE                COMMENT '매출총이익(TTM)/자산총계',
    FUND_RCEPT_NO   VARCHAR(14)           COMMENT '사용한 재무 공시 접수번호(PIT 감사추적)',
    CALCULATED_AT   DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (TICKER, TRADE_DATE),
    INDEX IDX_VAL_DATE_MARKETCAP (TRADE_DATE, MARKET_CAP)
) COMMENT='종목·일별 밸류에이션(소형주·4비율 랭킹)' ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;

-- 상장주식수 변경이력(KRX 권위값). 값이 바뀐 날만 한 행 → as-of(EFFECTIVE_DATE≤거래일 중 최신) 조회로 그 시점 주식수. 시총 계산의 PIT 입력.
CREATE TABLE IF NOT EXISTS STOCK_SHARE_COUNT (
    TICKER          VARCHAR(20)  NOT NULL COMMENT '종목코드',
    EFFECTIVE_DATE  DATE         NOT NULL COMMENT '이 주식수가 처음 관측된(=변경된) 거래일',
    LISTED_SHARES   BIGINT       NOT NULL COMMENT '상장주식수(KRX LIST_SHRS)',
    SOURCE          VARCHAR(10)  NOT NULL DEFAULT 'KRX' COMMENT '출처(KRX 등)',
    CREATED_AT      DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (TICKER, EFFECTIVE_DATE),
    INDEX IDX_SHARE_EFFECTIVE (EFFECTIVE_DATE)
) COMMENT='상장주식수 변경이력(as-of 조회)' ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;
