-- 사용자별 모델 점수 접근 권한 테이블 추가 (운영 증분 배포용, 멱등)
CREATE TABLE IF NOT EXISTS MEMBER_MODEL_GRANT (
    ID          BIGINT       NOT NULL AUTO_INCREMENT,
    MEMBER_ID   BIGINT       NOT NULL COMMENT '회원 ID',
    MODEL_ID    BIGINT       NOT NULL COMMENT '모델 ID',
    GRANTED_AT  DATETIME(6)  NOT NULL COMMENT '부여 일시',
    GRANTED_BY  BIGINT       COMMENT '부여한 관리자 회원 ID (null=시스템)',
    PRIMARY KEY (ID),
    UNIQUE KEY UK_MEMBER_MODEL_GRANT (MEMBER_ID, MODEL_ID),
    INDEX IDX_MMG_MEMBER_ID (MEMBER_ID),
    INDEX IDX_MMG_MODEL_ID (MODEL_ID)
) COMMENT='사용자별 모델 점수 접근 권한';
